DjangoCaptcha/DjangoCaptcha/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('code/', views.code, name='code'),
    url(r'^captcha/', include('captcha.urls')),
]

DjangoCaptcha/user/urls.py
from django.urls import path
from user import views

app_name = 'users'

urlpatterns = [
    # 第一种图片验证码方式: 自己使用PIL去制作验证码,并将验证码存在session中，在登录的时候进行校验
    path('login/', views.login, name='login'),


    # 第二种图片验证码方式: 用Django的 django-simple-captcha，再加上一个forms表单，
    # 将验证码存入mysql数据库中，app中导入captcha
    path('login_1/', views.user_login, name='login_1'),


    # 第三种图片验证码方式: 导入外部的一个包，用于生成图片验证码，存入redis中，
    # 由前端生成一个uuid码，用于标记二维码图片，前端传入的验证码和uuid，再拿到验证码跟从redis中取出来的uuid的值做对比
    # 用redis做缓存
    path('image_codes/', views.ImageCodeView.as_view()),
    path('login_2/', views.login_2,  name='login_2'),
]

DjangoCaptcha/user/models.py
from django.db import models

# Create your models here.

class UserInfo(models.Model):
    """
    用户：划分角色
    """
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=32, unique=True, verbose_name="用户名")  # 用户名设置成唯一值
    password = models.CharField(max_length=64, verbose_name="密码")
    real_name = models.CharField(max_length=50, verbose_name=u"真实姓名", default="")
    email = models.EmailField(max_length=254, unique=True, verbose_name="邮箱")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_time = models.DateTimeField(auto_now=True, verbose_name='更新时间')
    is_delete = models.BooleanField(default=False, verbose_name='删除标记')

    class Meta:
        db_table = 'user'
        verbose_name = '用户表'
        verbose_name_plural = verbose_name

DjangoCaptcha/user/forms.py
# forms.py
from django import forms
from captcha.fields import CaptchaField


class LoginForm(forms.Form):
    username = forms.CharField(max_length=20, min_length=3)
    password = forms.CharField(max_length=128, widget=forms.PasswordInput())
    captcha = CaptchaField()  # 验证码字段

DjangoCaptcha/user/views.py
from django.shortcuts import render,HttpResponse,redirect
# 从utils文件夹下的code文件导入 check_code
from Utlis.code import check_code
from .models import UserInfo
from .forms import LoginForm
from django.views import View
from django import http
from django_redis import get_redis_connection
from Utlis.captcha.captcha import captcha


def code(request):
    """
    生成图片验证码
    """
    img, random_code = check_code()
    request.session['random_code'] = random_code
    from io import BytesIO
    # 实现了在内存中操作bytes
    stream = BytesIO()
    # 将二维码最终转为png格式
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())


def login(request):
    """
    用户登陆
    """
    if request.method == 'GET':
        return render(request, 'login.html')
    user = request.POST.get('username')
    pwd = request.POST.get('password')
    code = request.POST.get('code')
    if code in [None, '']:
        return render(request, 'login.html', {'msg': '验证码没填'})
    if code.upper() != request.session['random_code'].upper():
        return render(request, 'login.html', {'msg': '验证码错误'})
    user = UserInfo.objects.filter(username=user, password=pwd)
    if user:
        return redirect('https://www.baidu.com')
    return render(request, 'login.html', {'msg': '用户名或密码错误'})


def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = UserInfo.objects.filter(username=username, password=password)
            if user:
                return redirect('https://www.baidu.com')
    else:
        form = LoginForm()
    # 跳转登录页面
    return render(request, 'user_login.html', context={'form':form})


class ImageCodeView(View):
    def get(self, request):
        # 生成图形验证码
        uuid = request.GET.get('uuid')
        print('UUID = ', uuid)
        text, image = captcha.generate_captcha()
        # 使用配置的redis数据库的别名，创建连接到redis的对象
        redis_conn = get_redis_connection('img_code')
        # redis_conn.setex('key', '过期时间', 'value')
        redis_conn.setex('img_%s' % uuid, 300, text)  # 有效时间是300秒
        # 响应图形验证码: image/jpg
        return http.HttpResponse(image, content_type='image/jpg')


def login_2(request):
    """
    用户登陆
    """
    if request.method == 'GET':
        return render(request,'login_2.html')
    user = request.POST.get('username')
    pwd = request.POST.get('password')
    code = request.POST.get('code')
    uuid = request.POST.get('uuid', '9b4381ed-06da-4ff6-ab56-56fbcbec5ef2')  # 先写死
    print(f'code = {code}  uuid = {uuid}')
    redis_conn = get_redis_connection('img_code')
    uuid_code = redis_conn.get(f'img_{uuid}')
    uuid_code = str(uuid_code, 'utf-8')
    print(f'uuid_code = {uuid_code}')
    if uuid_code in [None, '']:
        return render(request, 'login_2.html', {'msg': '验证码没填'})
    if code.upper() != uuid_code.upper():
        return render(request, 'login.html',{'msg':'验证码错误'})
    user = UserInfo.objects.filter(username=user, password=pwd)
    if user:
        return redirect('https://www.baidu.com')
    return render(request, 'login_2.html', {'msg': '用户名或密码错误'})


DjangoCaptcha/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'user:login' %}" method="post">
        {% csrf_token %}
        <p>
            <input type="text" name="username" placeholder="用户名" />
        </p>
        <p>
            <input type="password" name="password" placeholder="密码" />
        </p>
        <p>
            <input type="text" name="code" placeholder="验证" />
            <img onclick="changeImg(this);" src="/code/"  title="点击更换">
        </p>
        <input type="submit" value="提交">{{ msg }}
    </form>
    <script>
        // 通过changeImg事件来更换图片
        function changeImg(ths) {
            ths.src = ths.src + '?';
            console.log(ths.src);
        }
    </script>
</body>
</html>

DjangoCaptcha/templates/login_2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'user:login_2' %}" method="post">
        {% csrf_token %}
        <p>
            <input type="text" name="username" placeholder="用户名" />
        </p>
        <p>
            <input type="password" name="password" placeholder="密码" />
        </p>
        <p>
            <input type="text" name="code" placeholder="验证" />
            <img onclick="changeImg(this);" src="/user/image_codes/?uuid=9b4381ed-06da-4ff6-ab56-56fbcbec5ef2"  title="点击更换">
        </p>
        <input type="submit" value="提交">{{ msg }}
    </form>
    <script>
        // 通过changeImg事件来更换图片
        function changeImg(ths) {
            ths.src = ths.src + '?';
            console.log(ths.src);
        }
    </script>
</body>
</html>

DjangoCaptcha/templates/user_login.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
<div>{{ msg }}</div>
<form action="{% url 'user:login_1' %}" method="post">
    {% csrf_token %}
    用户：{{ form.username }} <span>{{ form.username.errors.0 }}</span> <br>
    密码：{{ form.password }} <span>{{ form.password.errors.0 }}</span><br>
    验证码：{{ form.captcha }} <span>{{ form.captcha.errors.0 }}</span><br>
    <input type="submit">
</form>
</body>
</html>
<script src="https://cdn.bootcss.com/jquery/1.12.3/jquery.min.js"></script>
<script>
     //点击刷新验证码
    $(function () {
        $('.captcha').css({
            'cursor': 'pointer'
        });
        // ajax刷新
        $('.captcha').click(function () {
            console.log('click');
            $.get("{% url 'captcha-refresh' %}",
                function (result) {
                    $('.captcha').attr('src', result['image_url']);
                    $('#id_captcha_0').val(result['key'])
                });
        });
    })
</script>